### ISSUE TITLE
Month parsing is returning dates from previous month

### ISSUE THREAD

**Issue by udayapitchika** [niklongstone/amazon-date-parser#1]
@niklongstone AMAZON.DATE slot gives this month as "2017-11". If I parse it using `amazon-date-parser`
I'm getting the object with dates from previous month.
```
{
endDate: Tue Oct 31 2017 19:59:59 GMT-0400 (EDT),
startDate: Sat Sep 30 2017 20:00:00 GMT-0400 (EDT)
}
```
I think the object should rather return the startDate as first day of the current month and endDate as either 
1. Date-time of now or
2. Last day of current month

For now, I'm adding 1 month to both startDate & endDate when a month is parsed.

Please check and let me know if I'm missing anything.

**Comment by niklongstone** [comment]
Hi @udayapitchika thanks for reporting that I am investigating the issue.
I will be back soon, I am assuming your system is under America/New York timezone? 
Is that correct?

**Comment by udayapitchika** [comment]
Thanks @niklongstone for responding. Correct, my system is using America/New York timezone.

**Comment by niklongstone** [comment]
Hi @udayapitchika, apparently the issue is related to timezones probably affects only months.
For instance, in your case endDate: Tue Oct 31 2017 19:59:59 GMT-0400 (EDT) is 4 hours difference, that's why is 19:59 instead of 23:59. Furthermore, the months is also wrong (should be Nov) due to a bug in the conversion.

Anyway, I am working on a fix, I should be able to roll out the next release this weekend.
Many thanks for reporting.
