### ISSUE TITLE
Can't handle quarters

### ISSUE THREAD

**Issue by tormodboga** [niklongstone/amazon-date-parser#3]
First off, great project!

Currently, it doesn't seem to handle quarters.. If I ask alexa about last quarter, it produces the value "2017-Q4". Unfortunately this crashes the parser:

```
Error: Invalid constructor parameter or parameter not supported.
    at new AmazonDateParser (/built_app/programs/server/npm/node_modules/amazon-date-parser/index.js:80:23)
```

Is this something you are considering adding in the future?

**Comment by niklongstone** [comment]
Hi @tormodboga the Amazon documentation doesn't explicitly mentioned quarters so, many thanks for flagging this. 

I think is pretty easy to implement and I am going to do it very soon.

Now the problem is what to return by default.
Are you expecting the first quarter to be "the first quarter of the year" so from 1st of Jan to end of Mar ?

I think I also should check Semesters, Trimesters and Bimesters maybe are implemented you never know.

**Comment by tormodboga** [comment]
Yes, Q1 must be from 1st of Jan to end of March.. and 2017Q4 is from 2017-10-01 to 2017-12-31 etc..

I have not seen evidence that they support the other periods you list..

**Comment by niklongstone** [comment]
I've added the feature, you can test it in advance using this branch:
https://github.com/niklongstone/amazon-date-parser/tree/feat/quarters
soon I will create a release.

**Comment by tormodboga** [comment]
Wow, speedy delivery :)
Thanks alot..
